export { default as Navbar } from './Navbar'
export { default as Services } from './Services'
export { default as Hero } from './Hero'
export { default as Specialist } from './Specialist'
export { default as Reason } from './Reason'
export { default as Testimonials } from './Testimonials'
export { default as Footer } from './Footer'
export { default as Articles } from './Articles'
